version: '3'
services:
  eventstore:
    image: eventstore/eventstore
    ports:
     - "2113:2113"
     - "1113:1113"
  test:
    build:
      context: .
    image: ameier38/ouroboros-test:latest
    environment:
      - EVENTSTORE_HOST=eventstore
      - EVENTSTORE_PORT=1113
      - EVENTSTORE_USER=admin
      - EVENTSTORE_PASSWORD=changeit
  helm-test:
    build:
      context: .
    image: ameier38/ouroboros-test:latest
    environment:
      - EVENTSTORE_PROTOCOL=discover
      - EVENTSTORE_HOST=localhost
      - EVENTSTORE_PORT=2113
      - EVENTSTORE_USER=admin
      - EVENTSTORE_PASSWORD=changeit
