provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  kube-test:
    lang: dockerfile
    handler: ./kube-test
    image: ameier38/ouroboros-kube-test:latest
    environment:
      write_debug: true
      EVENSTORE_PROTOCOL: discover
      EVENTSTORE_HOST: eventstore.ouroboros.svc.cluster.local
      EVENTSTORE_PORT: 1113
